const sections=[['01','Motion Foundations'],['02','Buttons & Touch'],['03','Menus & Navigation'],['04','Scroll-driven UI'],['05','Parallax & Depth'],['06','Sliders & Selectors'],['07','Carousels & Cards'],['08','Inventory & Drag'],['09','HUD & Progress'],['10','Lists & Collections'],['11','Popups & Overlays'],['12','Maps & Skill Trees'],['13','Mobile Controls'],['14','Special Elements'],['15','Effects Lab'],['16','Performance & A11y']];
const nav=document.querySelector('#nav'); nav.innerHTML=sections.map((s,i)=>`<a href="sections/section-${String(i+1).padStart(2,'0')}.html" class="${i?'':'active'}"><span>${s[0]} · ${s[1]}</span>${i?'':'★'}</a>`).join('');
const complete=new Set(); const saved=JSON.parse(localStorage.getItem('award-progress')||'[]'); saved.forEach(x=>complete.add(x));
function refresh(){const pct=Math.round(complete.size/3*100);document.querySelector('#progressText').textContent=Math.min(pct,100)+'%';document.querySelector('#progressBar').style.width=Math.min(pct,100)+'%';document.querySelector('.progress-card small').textContent=`${complete.size} из 76 золотых паттернов`;document.querySelectorAll('[data-complete]').forEach(b=>{if(complete.has(b.dataset.complete)){b.innerHTML='Пройдено ✓';b.style.color='#d8f56a'}})} refresh();
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)} window.showToast=showToast;
document.querySelectorAll('[data-complete]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.complete;complete.add(id);localStorage.setItem('award-progress',JSON.stringify([...complete]));refresh();showToast('Паттерн добавлен в прогресс · так держать')}));
const dot=document.querySelector('.demo-dot'), demo=document.querySelector('#timingDemo'); demo.addEventListener('pointerdown',e=>{const r=demo.getBoundingClientRect();dot.style.left=(e.clientX-r.left-5)+'px';dot.animate([{transform:'scale(1.8)'},{transform:'scale(1)'}],{duration:350,easing:'cubic-bezier(.2,1.6,.4,1)'});});
document.querySelector('.easing-demo').addEventListener('click',e=>{const b=e.currentTarget.querySelector('.ease-ball');b.animate([{left:'0%'},{left:'88%'}],{duration:850,easing:'cubic-bezier(.16,1.3,.3,1)'})});document.querySelector('.choreo-demo').addEventListener('click',e=>{[...e.currentTarget.children].forEach((x,i)=>x.animate([{transform:'translateY(0)',opacity:x.style.opacity||1},{transform:'translateY(-16px)',opacity:1},{transform:'translateY(0)'}],{duration:550,delay:i*90}))});
document.querySelector('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('light');showToast('В этом курсе тьма — часть атмосферы ✦')});document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#nav a').forEach(a=>a.style.display=a.textContent.toLowerCase().includes(q)?'flex':'none')});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#search').focus()}});

const modal=document.querySelector('#modal'), modalTitle=document.querySelector('#modalTitle'), modalText=document.querySelector('#modalText'), modalCode=document.querySelector('#modalCode');
const lessonData={timing:['Калибровка длительностей','Ритм — невидимая сетка, по которой пользователь считывает качество. 100 мс — реакция, 200 мс — микро-переход, 350 мс — смена контекста.','this.tweens.add({ targets: node, duration: 200, ease: "Cubic.Out" });'],easing:['Галерея easing','Одна цель может ощущаться как пластик, металл или пружина. Используй ease как часть характера бренда, а не случайный preset.','this.tweens.add({ targets: node, ease: "Back.Out", overshoot: 1.2 });'],choreo:['Anticipation → Action → Follow-through','Три акта превращают событие в понятный ритуал. Сначала подготовь взгляд, затем покажи действие, после — оставь след.','new Choreography(scene).at(0, anticipation).at(80, action).at(220, followThrough);']};
function openLesson(id){const d=lessonData[id];if(!d)return;modalTitle.textContent=d[0];modalText.textContent=d[1];modalCode.textContent=d[2];modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelector('#modalDemo span').animate([{transform:'scale(.4)',opacity:.3},{transform:'scale(1)',opacity:1}],{duration:500,easing:'cubic-bezier(.2,1.5,.4,1)'})}
document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>openLesson(b.dataset.complete)));document.querySelector('#modalClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.querySelector('#markDone').onclick=()=>{const id=Object.keys(lessonData).find(k=>lessonData[k][0]===modalTitle.textContent);if(id){complete.add(id);localStorage.setItem('award-progress',JSON.stringify([...complete]));refresh();showToast('Урок завершён — прогресс сохранён')}modal.classList.remove('open')};
function setting(id,cls){document.querySelector('#'+id).onchange=e=>document.body.classList.toggle(cls,e.target.checked)}setting('reduceMotion','reduce-motion');setting('leftHand','left-hand');setting('largeTouch','large-touch');document.querySelector('#settingsBtn').onclick=()=>document.querySelector('.control-strip').scrollIntoView({behavior:'smooth',block:'center'});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
const catalogGrid=document.querySelector('#catalogGrid');
const catalogInfo=[['Motion Foundations',8,'Тайминг · easing · choreography'],['Buttons & Touch',12,'Spring press · hold · morph'],['Menus & Navigation',38,'Gooey tabs · radial · pause'],['Scroll-driven UI',32,'Snap · coverflow · timelines'],['Parallax & Depth',22,'Gyro · DOF · holographic'],['Sliders & Selectors',44,'Rubber · knobs · pickers'],['Carousels & Cards',70,'FLIP · coverflow · reward'],['Inventory & Drag',28,'Magnet · merge · loot vacuum'],['HUD & Progress',63,'Health · cooldown · boss bar'],['Lists & Collections',23,'Virtual list · reorder · search'],['Popups & Overlays',33,'Sheets · coach marks · reveal'],['Maps & Skill Trees',34,'Fog · nodes · pinch zoom'],['Mobile Controls',27,'Joystick · aim · gestures'],['Special Elements',30,'Scratch · wheel · chest'],['Effects Lab',51,'Glass · foil · dissolve'],['Performance & A11y',12,'60 FPS · budgets · inclusive']];
catalogGrid.innerHTML=catalogInfo.map((x,i)=>`<article class="catalog-item ${i?'locked':''}" id="catalog-${i}"><span class="number">${String(i+1).padStart(2,'0')}</span><span class="count">${x[1]} PATTERNS</span><h4>${x[0]}</h4><p>${x[2]}</p></article>`).join('');
document.querySelectorAll('.catalog-item').forEach((el,i)=>el.onclick=()=>{if(i===0)document.querySelector('#motion').scrollIntoView({behavior:'smooth'});else showToast(`${catalogInfo[i][0]} · лаборатория в разработке`)});
const spring=document.querySelector('.spring-button');spring.addEventListener('pointerdown',()=>spring.animate([{transform:'scale(1)'},{transform:'scale(.91,.84)'},{transform:'scale(1.05)'},{transform:'scale(1)'}],{duration:420,easing:'cubic-bezier(.2,1.4,.4,1)'}));
const hold=document.querySelector('.hold-button'), ring=hold.querySelector('i');let holdTimer;hold.addEventListener('pointerdown',()=>{ring.style.transition='clip-path 1.2s linear';ring.style.clipPath='inset(0 0 0 0)';holdTimer=setTimeout(()=>{hold.querySelector('b').textContent='DONE ✓';hold.animate([{transform:'scale(1)'},{transform:'scale(1.2)'},{transform:'scale(1)'}],{duration:400})},1200)});['pointerup','pointerleave','pointercancel'].forEach(e=>hold.addEventListener(e,()=>{clearTimeout(holdTimer);if(hold.querySelector('b').textContent!=='DONE ✓'){ring.style.transition='clip-path .2s';ring.style.clipPath='inset(0 100% 0 0)'}}));document.querySelector('.liquid-button').addEventListener('pointerdown',e=>{e.currentTarget.classList.add('active');setTimeout(()=>e.currentTarget.classList.remove('active'),1000)});const morph=document.querySelector('.morph-button');morph.onclick=()=>{morph.classList.add('loading');morph.textContent='';setTimeout(()=>{morph.classList.remove('loading');morph.classList.add('success');},900)};
const healthNow=document.querySelector('.health-now'),healthDelay=document.querySelector('.health-delay');document.querySelector('#damageBtn').onclick=()=>{healthNow.style.width='38%';setTimeout(()=>healthDelay.style.width='38%',450);showToast('Delayed damage: сначала факт, затем объяснение')};const ringProgress=document.querySelector('.ring-progress'),coolVal=document.querySelector('#cooldownValue');document.querySelector('#cooldownBtn').onclick=()=>{ringProgress.style.strokeDashoffset='245';let n=0;const t=setInterval(()=>{n+=2;coolVal.textContent=n;if(n>=100){clearInterval(t);ringProgress.style.strokeDashoffset='0'}},18)};let coins=240;document.querySelector('#coinBtn').onclick=()=>{coins+=10;document.querySelector('#counterValue').textContent=String(coins).padStart(4,'0');const c=document.querySelector('.coin');c.animate([{transform:'translate(-90px,-40px) scale(1.4)'},{transform:'translate(0,0) scale(1)'}],{duration:550,easing:'cubic-bezier(.2,1.3,.4,1)'})};document.querySelector('#bossBtn').onclick=()=>{const b=document.querySelector('.boss-demo');b.classList.add('revealed');showToast('Cinematic reveal: letterbox → bar → phase')};
const phone=document.querySelector('.phone-screen');phone.addEventListener('pointermove',e=>{const r=phone.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;phone.style.transform=`perspective(700px) rotateY(${x*8}deg) rotateX(${-y*8}deg)`});phone.addEventListener('pointerleave',()=>phone.style.transform='');document.querySelector('#menuPause').onclick=()=>{document.querySelector('.phone-frame').classList.toggle('pause-mode');showToast('Pause state: game context preserved, attention redirected')};
const sceneRange=document.querySelector('#sceneRange');sceneRange.oninput=e=>{const v=+e.target.value;document.querySelector('#scrollProgress').style.height=v+'%';const scene=document.querySelector('#scrollScene');scene.style.transform=`scale(${1+v/500}) translateY(${-v/7}px)`;scene.style.filter=`saturate(${1+v/90})`;document.querySelector('.scene-star').style.transform=`translate(${-v/2}px,${v/3}px) rotate(${v*1.8}deg)`;document.querySelector('.scene-card').style.transform=`translateY(${-v/2}px) rotate(${8-v/10}deg) scale(${1+v/300})`;document.querySelector('.scene-copy small').textContent=v>72?'02 — 04':'01 — 04';};
